apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab1-deployment
  labels:
    app: lab1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lab1
  template:
    metadata:
      labels:
        app: lab1
    spec:
      containers:
      - name: lab1
        image: mwaijohng/static:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8000